### ISSUE TITLE
ChannelLayerMask: MultiSection of ChannelLayers on MultiLayerSelection

### ISSUE THREAD

**Issue by campi3d** [campi3d/MARI-Extension-Pack#93]
File "C:/Users/JensK/Documents/Mari/Scripts\Tools\Layers\extPack_channel_layer.py", line 228, in <lambda>
    ok_button.clicked.connect(lambda: self.runCreate(mode,channel_list,Invert_box.isChecked()))
  File "C:/Users/JensK/Documents/Mari/Scripts\Tools\Layers\extPack_channel_layer.py", line 288, in runCreate
    makeChannelLayer(sourceChannel,mode,invert)
  File "C:/Users/JensK/Documents/Mari/Scripts\Tools\Layers\extPack_channel_layer.py", line 150, in makeChannelLayer
    layerMaskStack.removeLayers(existingLayer)
ValueError: Layer(s) not in layer stack
Traceback (most recent call last):
  File "C:/Users/JensK/Documents/Mari/Scripts\Tools\Layers\extPack_channel_layer.py", line 228, in <lambda>
    ok_button.clicked.connect(lambda: self.runCreate(mode,channel_list,Invert_box.isChecked()))
  File "C:/Users/JensK/Documents/Mari/Scripts\Tools\Layers\extPack_channel_layer.py", line 288, in runCreate
    makeChannelLayer(sourceChannel,mode,invert)
  File "C:/Users/JensK/Documents/Mari/Scripts\Tools\Layers\extPack_channel_layer.py", line 150, in makeChannelLayer
    layerMaskStack.removeLayers(existingLayer)
ValueError: Layer(s) not in layer stack

**Comment by campi3d** [comment]
fixed.
